pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Quickshell
import Quickshell.Io
import "../Theme"

/*
`khal configure` gives following config options which should be generated by quickshell
and be able to be edited through the quickshell settings:

What ordering of year, month, date do you want to use?
[0] year-month-day (today: 2026-08-04)
[1] day/month/year (today: 04/08/2026)
[2] month/day/year (today: 08/04/2026)
[3] Custom

What timeformat do you want to use?
[0] 24 hour clock (recommended)
[1] 12 hour clock

Event fields:
+ title
+ description
+ start-date-long
- end-date-long
+ start-time
+ end-time
+ duration
- uid (useless prolly)
+ repeat-symbol
- alarms-list
- location
+ calendar
+ calendar-color
- url
+ all-day

*/
ColumnLayout {
    id: root
    spacing: 5

    property date selectedDate
    property string formattedDate: Qt.formatDateTime(root.selectedDate, "yyyy-MM-dd")

    function formatRelativeDate(date) {
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        const target = new Date(date);
        target.setHours(0, 0, 0, 0);

        const diffDays = Math.round((target - today) / (1000 * 60 * 60 * 24));

        if (diffDays === 0)
            return "Today";
        if (diffDays === 1)
            return "Tomorrow";
        if (diffDays === -1)
            return "Yesterday";

        return Qt.formatDate(date, "dd/MM/yyyy");
    }

    function openConfigWindow() { //TODO: remove hardcoded path
        Quickshell.execDetached(["qs", "ipc", "call", "khal_config_window", "open"]);
    }

    function openEventAddWindow() { //TODO: remove hardcoded path
        Quickshell.execDetached(["qs", "ipc", "call", "event_add_window", "open", formattedDate]);
    }

    RowLayout {
        Layout.alignment: Qt.AlignRight | Qt.AlignTop
        spacing: 10

        Text {
            text: "Configure Calendars"
            color: Theme.font
            font.family: Theme.fontFamily
            font.pixelSize: Theme.fontSize - 2
        }

        Rectangle {
            Layout.preferredHeight: 24
            Layout.preferredWidth: 24
            color: settingsMouse.containsMouse ? Theme.secondary : "transparent"
            radius: 12

            Image {
                anchors.centerIn: parent
                source: "../icons/settings.svg"
                sourceSize.width: 20
                sourceSize.height: 20
                width: 20
                height: 20
                fillMode: Image.PreserveAspectFit
            }

            MouseArea {
                id: settingsMouse
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: {
                    root.openConfigWindow();
                }
            }
        }
    }

    RowLayout {
        Layout.fillWidth: true
        Layout.alignment: Qt.AlignLeft
        Layout.margins: 5

        Text {
            text: "Events \u2022 " + root.formatRelativeDate(root.selectedDate)
            color: Theme.font
            font.family: Theme.fontFamily
        }

        Rectangle {
            Layout.fillWidth: true
            Layout.preferredHeight: 1
            color: Theme.primary
        }

        Rectangle {
            Layout.preferredHeight: 24
            Layout.preferredWidth: 24
            color: addMouse.containsMouse ? Theme.secondary : "transparent"
            radius: 12

            Image {
                anchors.centerIn: parent
                source: Quickshell.iconPath("list-add")
                sourceSize.width: 20
                sourceSize.height: 20
                width: 20
                height: 20
                fillMode: Image.PreserveAspectFit
            }

            MouseArea {
                id: addMouse
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: root.openEventAddWindow()
            }
        }
    }

    Rectangle {
        Layout.fillHeight: true
        Layout.fillWidth: true
        Layout.margins: 5

        color: Theme.primary
        radius: 12

        ScrollView {
            anchors.fill: parent
            anchors.margins: 10
            clip: true

            ColumnLayout {
                id: eventsLayout
                width: parent.width

                property var selectedEvent

                Repeater {
                    model: KhalConfig.events.lookup[root.formattedDate]
                    delegate: EventCard {
                        required property var modelData
                        event: modelData
                        selected: eventsLayout.selectedEvent === this
                        Layout.fillWidth: true

                        onClicked: {
                            if (eventsLayout.selectedEvent === this) {
                                eventsLayout.selectedEvent = null;
                                return;
                            }
                            eventsLayout.selectedEvent = this;
                        }
                    }
                }
            }
        }
    }
}
