-- Generated by nwg-displays on 2026-09-15 at 16:57:37. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "0x0",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "1920x0",
    scale = 1,
    vrr = 0
})
